#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\MX1MR41/ permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
