#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me

A301_RED="\\\trewrite ^/redirect_me https://github.com/MX1MR41 permanent;"

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "30i $A301_RED" /etc/nginx/sites-available/default
sudo service nginx restart
